ci: adicionar paso al workflow

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -15,3 +15,12 @@ jobs:
 
       - name: Mensaje de prueba
         run: echo "CI funcionando correctamente"
+
+      - name: Verificar HTML
+        run: |
+          if grep -q "<html" index.html; then
+            echo "HTML válido"
+          else
+            echo "Error en HTML"
+            exit 1
+          fi
